### ISSUE TITLE
Make command line tool

### ISSUE THREAD

**Issue by vladimirkovacevic** [kilibardajovica/gi-project#1]
Most bioinformatics tools are able to be executed from command line. Can you pack your sequencer simulator code into python script that parses necessary command-line parameters? It is convenient to use docopt, but of course not necessary. Thanks.

**Comment by kilibardajovica** [comment]
I wrote and uploaded python script 'script.py' which can be used from command-line for quicker execution of simulator. Also, I updated README to include instructions on how to run script

**Comment by vladimirkovacevic** [comment]
Running from the command line assumes it is possible to set the parameters from it. In script.py all parameters are hardcoded. [Here](https://github.com/sbg/smart-variant-filtering/blob/master/svf_apply.py) is an example of parsing command line parameters, it should be very straightforward to adapt it for your use case.

**Comment by kilibardajovica** [comment]
But it is possible to set parameters from script.py. For example running it like
python script.py -g Test.fa -c 3 -q 25 -r 10 -f 25 -s 0.01 -i 0.0001 -d 0.0001
will set parameter to these values. They are just initialized on start in case some of them is not set in command line, they are not really hardcoded.

**Comment by vladimirkovacevic** [comment]
OK, I see. Thanks. Maybe you could just rename script.py to sequencing_simulator.py
